# This config defines the server block of the G-nom web interface.
# This config includes no SSL certificates but can be upgraded easily using certbot for Let's Encrypt certificates.

server {
    listen 80;
    index index.php index.html;

    # Increase as needed for large file uploads
    client_max_body_size 8G;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    root /var/www/public;

    # Use the php-fpm container
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Serve static files
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
